import createClient from "openapi-fetch";
import type { paths } from "./v1"; // generated by openapi-typescript

export const client = createClient<paths>({ baseUrl: "http://localhost:5011/" });

const {data: d} = await client.GET("/api/campaigns/{id}", {
    params: { path: { id: 0 }, }
});

console.log(d)
