import createClient from "openapi-fetch";
import type { paths, components } from "./v1"; // generated by openapi-typescript

export const client = createClient<paths>({ baseUrl: process.env.NEXT_PUBLIC_API_URL, credentials: "include" });

export type CampaignObject = components["schemas"]["RecruitmentCampaignGetDto"];
export enum CampaignPriority {
	LOW = 0,
	MEDIUM = 1,
	HIGH = 2,
}

export type CampaignPostingObject = components["schemas"]["CampaignPostingGetDto"];
export enum PostingStatus {
	OPEN = 0,
	CLOSED = 1,
}

export type JobPostingObject = components["schemas"]["JobPostingGetDto"];

export type CandidateObject = components["schemas"]["CandidateGetDto"];
export type ExperienceObject = components["schemas"]["CandidateExperienceGetDto"];
export type JobApplication = components["schemas"]["JobApplicationGetDto"];

export enum ApplicantStatus {
	APPLIED = 0,
	PENDING = 1,
	REJECTED = 2,
	ACCEPTED = 3,
}

export type User = components["schemas"]["UserGetDto"];
export enum UserType {
	HIRING_MANAGER = 0,
	RECRUITER = 1,
}
