import createClient from "openapi-fetch";
import type { paths, components } from "./v1"; // generated by openapi-typescript

export const client = createClient<paths>({ baseUrl: process.env.NEXT_PUBLIC_API_URL });

export type CampaignObject = components["schemas"]["RecruitmentCampaignGetDto"];
export enum CampaignPriority {
	LOW = 0,
	MEDIUM = 1,
	HIGH = 2,
}
export type CandidateObject = components["schemas"]["CandidateGetDto"];
export type ExperienceObject = components["schemas"]["CandidateExperienceGetDto"];
