/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CandidateGetDto"];
                        "application/json": components["schemas"]["CandidateGetDto"];
                        "text/json": components["schemas"]["CandidateGetDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RecruitmentCampaignGetDto"][];
                        "application/json": components["schemas"]["RecruitmentCampaignGetDto"][];
                        "text/json": components["schemas"]["RecruitmentCampaignGetDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecruitmentCampaignCreateDto"];
                    "text/json": components["schemas"]["RecruitmentCampaignCreateDto"];
                    "application/*+json": components["schemas"]["RecruitmentCampaignCreateDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RecruitmentCampaignGetDto"];
                        "application/json": components["schemas"]["RecruitmentCampaignGetDto"];
                        "text/json": components["schemas"]["RecruitmentCampaignGetDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RecruitmentCampaignGetDto"];
                        "application/json": components["schemas"]["RecruitmentCampaignGetDto"];
                        "text/json": components["schemas"]["RecruitmentCampaignGetDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CampaignPriority: number;
        CandidateExperienceGetDto: {
            companyName: string;
            jobName: string;
            /** Format: date-time */
            dateStarted: string;
            /** Format: date-time */
            dateFinished?: string | null;
            /** Format: int32 */
            id?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CandidateGetDto: {
            firstName: string;
            lastName: string;
            experiences: components["schemas"]["CandidateExperienceGetDto"][];
            /** Format: int32 */
            id?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        };
        RecruitmentCampaignCreateDto: {
            name: string;
            priority: components["schemas"]["CampaignPriority"];
        };
        RecruitmentCampaignGetDto: {
            name: string;
            priority: components["schemas"]["CampaignPriority"];
            /** Format: int32 */
            id?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
