/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/auth/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["UserLoginDto"];
					"text/json": components["schemas"]["UserLoginDto"];
					"application/*+json": components["schemas"]["UserLoginDto"];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["UserGetDto"];
						"application/json": components["schemas"]["UserGetDto"];
						"text/json": components["schemas"]["UserGetDto"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/auth/register": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["UserCreateDto"];
					"text/json": components["schemas"]["UserCreateDto"];
					"application/*+json": components["schemas"]["UserCreateDto"];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["UserGetDto"];
						"application/json": components["schemas"]["UserGetDto"];
						"text/json": components["schemas"]["UserGetDto"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/auth/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["UserGetDto"];
						"application/json": components["schemas"]["UserGetDto"];
						"text/json": components["schemas"]["UserGetDto"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/Candidates": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["CandidateGetDto"];
						"application/json": components["schemas"]["CandidateGetDto"];
						"text/json": components["schemas"]["CandidateGetDto"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/applications": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: {
					postingId?: number;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["JobApplicationGetDto"][];
						"application/json": components["schemas"]["JobApplicationGetDto"][];
						"text/json": components["schemas"]["JobApplicationGetDto"][];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/applications/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["JobApplicationGetDto"];
						"application/json": components["schemas"]["JobApplicationGetDto"];
						"text/json": components["schemas"]["JobApplicationGetDto"];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/applications/{id}/reject": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["JobApplicationGetDto"];
						"application/json": components["schemas"]["JobApplicationGetDto"];
						"text/json": components["schemas"]["JobApplicationGetDto"];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/applications/{id}/accept": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["JobApplicationGetDto"];
						"application/json": components["schemas"]["JobApplicationGetDto"];
						"text/json": components["schemas"]["JobApplicationGetDto"];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/applications/{id}/plan-meeting": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["ApplicationMeetingPlanDto"];
					"text/json": components["schemas"]["ApplicationMeetingPlanDto"];
					"application/*+json": components["schemas"]["ApplicationMeetingPlanDto"];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["RecruitmentStageMeetingGetDto"];
						"application/json": components["schemas"]["RecruitmentStageMeetingGetDto"];
						"text/json": components["schemas"]["RecruitmentStageMeetingGetDto"];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/applications/{id}/log-meeting": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["ApplicationMeetingLogDto"];
					"text/json": components["schemas"]["ApplicationMeetingLogDto"];
					"application/*+json": components["schemas"]["ApplicationMeetingLogDto"];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["RecruitmentStageMeetingGetDto"];
						"application/json": components["schemas"]["RecruitmentStageMeetingGetDto"];
						"text/json": components["schemas"]["RecruitmentStageMeetingGetDto"];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/postings": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: {
					campaignId?: number;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["CampaignPostingGetDto"][];
						"application/json": components["schemas"]["CampaignPostingGetDto"][];
						"text/json": components["schemas"]["CampaignPostingGetDto"][];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/postings/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["JobPostingGetDto"];
						"application/json": components["schemas"]["JobPostingGetDto"];
						"text/json": components["schemas"]["JobPostingGetDto"];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["CandidateCreateDto"];
					"text/json": components["schemas"]["CandidateCreateDto"];
					"application/*+json": components["schemas"]["CandidateCreateDto"];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["JobPostingGetDto"];
						"application/json": components["schemas"]["JobPostingGetDto"];
						"text/json": components["schemas"]["JobPostingGetDto"];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/postings/{id}/close": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["JobPostingGetDto"];
						"application/json": components["schemas"]["JobPostingGetDto"];
						"text/json": components["schemas"]["JobPostingGetDto"];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/campaigns": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["RecruitmentCampaignGetDto"][];
						"application/json": components["schemas"]["RecruitmentCampaignGetDto"][];
						"text/json": components["schemas"]["RecruitmentCampaignGetDto"][];
					};
				};
			};
		};
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["RecruitmentCampaignCreateDto"];
					"text/json": components["schemas"]["RecruitmentCampaignCreateDto"];
					"application/*+json": components["schemas"]["RecruitmentCampaignCreateDto"];
				};
			};
			responses: {
				/** @description Created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["RecruitmentCampaignGetDto"];
						"application/json": components["schemas"]["RecruitmentCampaignGetDto"];
						"text/json": components["schemas"]["RecruitmentCampaignGetDto"];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/campaigns/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["RecruitmentCampaignGetDto"];
						"application/json": components["schemas"]["RecruitmentCampaignGetDto"];
						"text/json": components["schemas"]["RecruitmentCampaignGetDto"];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/campaigns/{id}/create-posting": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["JobPostingCreateDto"];
					"text/json": components["schemas"]["JobPostingCreateDto"];
					"application/*+json": components["schemas"]["JobPostingCreateDto"];
				};
			};
			responses: {
				/** @description Created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["JobPostingGetDto"];
						"application/json": components["schemas"]["JobPostingGetDto"];
						"text/json": components["schemas"]["JobPostingGetDto"];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/stages": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: {
					stageId?: number;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["RecruitmentStageGetDto"][];
						"application/json": components["schemas"]["RecruitmentStageGetDto"][];
						"text/json": components["schemas"]["RecruitmentStageGetDto"][];
					};
				};
			};
		};
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["GenericRecruitmentStageCreateDto"];
					"text/json": components["schemas"]["GenericRecruitmentStageCreateDto"];
					"application/*+json": components["schemas"]["GenericRecruitmentStageCreateDto"];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["RecruitmentStageGetDto"];
						"application/json": components["schemas"]["RecruitmentStageGetDto"];
						"text/json": components["schemas"]["RecruitmentStageGetDto"];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/stages/{stageId}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					stageId: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["RecruitmentStageGetDto"];
						"application/json": components["schemas"]["RecruitmentStageGetDto"];
						"text/json": components["schemas"]["RecruitmentStageGetDto"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		ApplicantDto: {
			firstName: string;
			lastName: string;
			email: string;
			/** Format: int32 */
			id: number;
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		ApplicationMeetingLogDto: {
			/** Format: int32 */
			meetingId: number;
			/** Format: int32 */
			grade: number;
			comment: string;
		};
		ApplicationMeetingPlanDto: {
			/** Format: date */
			date: string;
			/** Format: int32 */
			recruitmentStageId: number;
			/** Format: int32 */
			applicationId: number;
		};
		ApplicationStatus: number;
		CampaignPostingGetDto: {
			jobName: string;
			/** Format: date-time */
			datePosted: string;
			description: string;
			status: components["schemas"]["PostingStatus"];
			/** Format: int32 */
			id: number;
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		CampaignPriority: number;
		CandidateCreateDto: {
			firstName: string;
			lastName: string;
			email: string;
			experiences: components["schemas"]["CandidateExperienceCreateDto"][];
			/** Format: int32 */
			id: number;
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		CandidateExperienceCreateDto: {
			companyName: string;
			jobName: string;
			/** Format: date-time */
			dateStarted: string;
			/** Format: date-time */
			dateFinished?: string | null;
			/** Format: int32 */
			id: number;
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		CandidateExperienceGetDto: {
			companyName: string;
			jobName: string;
			/** Format: date-time */
			dateStarted: string;
			/** Format: date-time */
			dateFinished?: string | null;
			/** Format: int32 */
			id: number;
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		CandidateGetDto: {
			firstName: string;
			lastName: string;
			email: string;
			experiences: components["schemas"]["CandidateExperienceGetDto"][];
			/** Format: int32 */
			id: number;
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		GenericRecruitmentStageCreateDto: {
			technologyName?: string | null;
			teamName?: string | null;
			values?: string[];
			description: string;
			/** Format: int32 */
			postingId: number;
			recruiterId?: string;
		};
		JobApplicationGetDto: {
			/** Format: date-time */
			dateApplied: string;
			status: components["schemas"]["ApplicationStatus"];
			/** Format: int32 */
			postingId: number;
			/** Format: int32 */
			applicantId: number;
			posting?: components["schemas"]["CampaignPostingGetDto"];
			applicant?: components["schemas"]["ApplicantDto"];
			/** Format: int32 */
			id: number;
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		JobPostingCreateDto: {
			/** Format: date-time */
			datePosted: string;
			/** Format: int32 */
			campaignId?: number;
			status: components["schemas"]["PostingStatus"];
			jobName: string;
			description: string;
		};
		JobPostingGetDto: {
			jobName: string;
			/** Format: date-time */
			datePosted: string;
			description: string;
			status: components["schemas"]["PostingStatus"];
			/** Format: int32 */
			campaignId: number;
			campaign: components["schemas"]["PostingCampaignDto"];
			applications: components["schemas"]["JobApplicationGetDto"][];
			/** Format: int32 */
			id: number;
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		PostingCampaignDto: {
			name: string;
			priority: components["schemas"]["CampaignPriority"];
			/** Format: int32 */
			id: number;
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		PostingStatus: number;
		ProblemDetails: {
			type?: string | null;
			title?: string | null;
			/** Format: int32 */
			status?: number | null;
			detail?: string | null;
			instance?: string | null;
		};
		RecruiterType: number;
		RecruitmentCampaignCreateDto: {
			name: string;
			priority: components["schemas"]["CampaignPriority"];
		};
		RecruitmentCampaignGetDto: {
			name: string;
			priority: components["schemas"]["CampaignPriority"];
			postings: components["schemas"]["CampaignPostingGetDto"][];
			/** Format: int32 */
			id: number;
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		RecruitmentStageGetDto: {
			description: string;
			posting: components["schemas"]["CampaignPostingGetDto"];
			/** Format: int32 */
			id: number;
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		RecruitmentStageMeetingGetDto: {
			/** Format: date */
			date: string;
			/** Format: int32 */
			grade?: number | null;
			comment?: string | null;
			stage: components["schemas"]["RecruitmentStageGetDto"];
			application: components["schemas"]["JobApplicationGetDto"];
			/** Format: int32 */
			id: number;
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		UserCreateDto: {
			firstName: string;
			lastName: string;
			password: string;
			email: string;
			userType: components["schemas"]["UserType"];
			type?: components["schemas"]["RecruiterType"];
			department?: string | null;
		};
		UserGetDto: {
			id: string;
			firstName: string;
			lastName: string;
			email: string;
			userType: components["schemas"]["UserType"];
		};
		UserLoginDto: {
			email: string;
			password: string;
		};
		UserType: number;
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
