import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PropsWithChildren } from "react";
import { Megaphone } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" data-theme="ezhire">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-base-200`}
      >
        <div className="drawer lg:drawer-open">
          <input
            id="my-drawer"
            type="checkbox"
            className="drawer-toggle"
            checked
            readOnly
          />
          <div className="drawer-content">
            <div className="navbar lg:px-6 px-2">
              <div className="breadcrumbs text-sm">
                <ul>
                  <li>
                    <a>Kampanie</a>
                  </li>
                  <li>
                    <a>Rekrutacje</a>
                  </li>

                  <li>Frontend Developer (Ember.js)</li>
                </ul>
              </div>
            </div>
            <main className="bg-base-200 min-h-screen lg:p-6 p-2">
              <div className="bg-background rounded-md min-h-full p-5">
                {children}
              </div>
            </main>
          </div>
          <aside className="drawer-side">
            <label
              htmlFor="my-drawer"
              aria-label="close sidebar"
              className="drawer-overlay"
            ></label>
            <ul className="menu bg-background text-base-content min-h-full w-80 p-4">
              <h2 className="text-2xl font-bold text-blue-600 mb-4">EzHire</h2>
              <li>
                <a>
                  <Megaphone size={18} />
                  Kampanie
                </a>
                <ul>
                  <li>
                    <a>Ogłoszenia</a>
                  </li>
                </ul>
              </li>
            </ul>
          </aside>
        </div>
      </body>
    </html>
  );
}
